#!/usr/bin/env sh

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants 
SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components


PADDINGS=5 # All paddings use this value (icon, label, background and bar paddings)

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=2

SHADOW=on

#         --bar is for:
##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

#          --defalut is for:
##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --bar     height=35                                         \
                     color=$BAR_COLOR                                  \
                     shadow=on                                         \
                     position=top                                      \
                     sticky=on                                         \
                     padding_right=7                                   \
                     padding_left=7                                    \
                     corner_radius=50                                   \
                     y_offset=0                                       \
                     margin=0                                        \
                     blur_radius=20                                    \
                     notch_width=0                                     \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Bold:14.0"                       \
                     icon.color=$ICON_COLOR                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$FONT:Semibold:13.0"                  \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     background.padding_right=$PADDINGS                \
                     background.padding_left=$PADDINGS                 \
                     background.height=26                              \
                     background.corner_radius=7                        \
                     popup.background.border_width=4                   \
                     popup.background.corner_radius=7                 \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=on

##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces


##### Adding Left Items #####
# We add some regular items to the left side of the bar
# only the properties deviating from the current defaults need to be set

# Uncomment to add apple logo with functionalities: source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
#source "$ITEM_DIR/front_app.sh"

##### Adding Center Items #####
source "$ITEM_DIR/calendar.sh"

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/weather.sh"

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration and
# should never be run in an item script.

sketchybar --update

echo "sketchybar configuration loaded.."
