#!/usr/bin/env sh

# You can check the repo here: <https://github.com/koekeishiya/yabai>

# Unload the macOS WindowManager process
#launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

#-----------------#
# global settings #
#-----------------#

# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus          off

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse          off

# enabeling custom bar padding
yabai -m config external_bar               all:39:0

#??
#yabai -m config window_origin_display        default

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement             second_child

# Flooating windows are always on top (default: off)
yabai -m config window_topmost               off

# Modify window shadows (default: on, options: on, off, float)
# Example: show shadows only for floating windows
yabai -m config window_shadow                float

# window opacity (default: off)
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.15
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95

# ??
yabai -m config window_border                off
yabai -m config window_border_width          2
yabai -m config window_border_radius         11
yabai -m config active_window_border_color   0xffe1e3e4
yabai -m config normal_window_border_color   0xff2a2f38
yabai -m config insert_feedback_color        0xff9dd274
yabai -m config window_animation_duration    0.15

# If auto balance is disabled, the split ratio defines how much space 
# each window occupies after a new split is created. 
# A value of 0.5 means that both old and new window occupy the same space; 
# a value of 0.2 means that the old window occupies 20% of the available space 
# and the new window occupies 80% of the available space. 
# New windows are inserted at the right or bottom side. 
# The ratio needs to be between 0 and 1.
# Floating point value between 0 and 1 (default: 0.5)
yabai -m config split_ratio                  0.50

# Auto balance makes it so all windows always occupy the same space,
# independent of how deeply nested they are in the window tree.
# When a new window is inserted or a window is removed,
# the split ratios will be automatically adjusted.
yabai -m config auto_balance                 off

# Set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier               fn

# Set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1                move

# Set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2                resize

# When you drag a tiled window onto another, 
# yabai will either swap their positions in the window tree, 
# or modify the window tree by splitting the region occupied by the window.
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   8

# apps to not manage (ignore)
yabai -m rule --add app="^(LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|System Preferences|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m config --space 5 layout float
yabai -m config --space 6 layout float


yabai -m config layout bsp

echo "yabai configuration loaded.."
